### ISSUE TITLE
error on processing pdf

### ISSUE THREAD

**Issue by aleeusgr** [rybinmj/pdf_to_wordcloud#1]
processing 30 page document.
```
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pdf_wordcloud/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 451, in generate_from_frequencies
    font_size = int(2 * sizes[0] * sizes[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pdf_wordcloud/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 457, in generate_from_frequencies
    font_size = sizes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/pdf_wordcloud/bin/pdf", line 8, in <module>
    sys.exit(pdf())
  File "/home/alex/anaconda3/envs/pdf_wordcloud/lib/python3.10/site-packages/pdf_to_wordcloud/pdf_to_wordcloud.py", line 108, in pdf
    ).generate_from_frequencies(dct)
  File "/home/alex/anaconda3/envs/pdf_wordcloud/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 459, in generate_from_frequencies
    raise ValueError(
ValueError: Couldn't find space to draw. Either the Canvas size is too small or too much of the image is masked out.

```

suggestion: provide test pdf in docs
thank you

**Comment by rybinmj** [comment]
Apologies for the long delay. I wasn't able to consistently recreate your error with a 100+ page pdf. 

Here's an example of downloading the pdf of The Great Gatsby and creating a word cloud (assumes pdf_to_wordcloud is already pip installed). 

```
curl https://www.wsfcs.k12.nc.us/cms/lib/NC01001395/Centricity/Domain/7935/Gatsby_PDF_FullText.pdf --output gatsby.pdf
pdf gatsby.pdf -r said -s
```

I touched up a couple minor things in the meantime and will publish version 0.0.3. Let me know if you are still having issues and I can dive in a little deeper. Thanks!
